spring:
  profiles:
    active: local
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /static/**



  devtools:
    livereload:
      enabled: true

  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/codingjoa_boot
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  web:
    resources:
      add-mappings: true

server:
  port: 8080
  servlet:
    context-path: /condingjoa_boot/

logging:
  level:
    org.hibernate.sql: info
